version: 2.0.{branch}.{build}
image: Visual Studio 2017
configuration: Release
platform: WIN32
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: cd solution\vs2017\
build:
  project: nuiCore.sln
  verbosity: minimal
after_build:
- cmd: cd ..\..\
test_script:
- cmd: >-
    vstest.console build\tests\Win32\Release\nuiSystemTests.dll

    vstest.console build\tests\Win32\Release\nuiModuleTests.dll